language: c

dist: trusty

addons:
 apt:
   sources:
   - ubuntu-toolchain-r-test
   packages:
   - gcc-4.8
   - g++-4.8

script: 
   - mkdir build
   - cd ./build
   - cmake ../
   - make
   - cd ./bin
   - ./translateTest
