language: c

dist: trusty

addons:
 apt:
   sources:
   - ubuntu-toolchain-r-test
   packages:
   - gcc-4.8
   - g++-4.8
 apt:
    sources:
      - george-edison55-precise-backports
    packages:
      - cmake
      - cmake-data

script: 
   - mkdir build
   - cd ./build
   - cmake ../
   - make
   - cd ./bin
   - ./translateTest
